/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	firefly_v1 "github.com/frodehus/firefly/pkg/apis/firefly/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFireflyApplications implements FireflyApplicationInterface
type FakeFireflyApplications struct {
	Fake *FakePepperprovesapointV1
	ns   string
}

var fireflyapplicationsResource = schema.GroupVersionResource{Group: "pepperprovesapoint.com", Version: "v1", Resource: "fireflyapplications"}

var fireflyapplicationsKind = schema.GroupVersionKind{Group: "pepperprovesapoint.com", Version: "v1", Kind: "FireflyApplication"}

// Get takes name of the fireflyApplication, and returns the corresponding fireflyApplication object, and an error if there is any.
func (c *FakeFireflyApplications) Get(name string, options v1.GetOptions) (result *firefly_v1.FireflyApplication, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(fireflyapplicationsResource, c.ns, name), &firefly_v1.FireflyApplication{})

	if obj == nil {
		return nil, err
	}
	return obj.(*firefly_v1.FireflyApplication), err
}

// List takes label and field selectors, and returns the list of FireflyApplications that match those selectors.
func (c *FakeFireflyApplications) List(opts v1.ListOptions) (result *firefly_v1.FireflyApplicationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(fireflyapplicationsResource, fireflyapplicationsKind, c.ns, opts), &firefly_v1.FireflyApplicationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &firefly_v1.FireflyApplicationList{ListMeta: obj.(*firefly_v1.FireflyApplicationList).ListMeta}
	for _, item := range obj.(*firefly_v1.FireflyApplicationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested fireflyApplications.
func (c *FakeFireflyApplications) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(fireflyapplicationsResource, c.ns, opts))

}

// Create takes the representation of a fireflyApplication and creates it.  Returns the server's representation of the fireflyApplication, and an error, if there is any.
func (c *FakeFireflyApplications) Create(fireflyApplication *firefly_v1.FireflyApplication) (result *firefly_v1.FireflyApplication, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(fireflyapplicationsResource, c.ns, fireflyApplication), &firefly_v1.FireflyApplication{})

	if obj == nil {
		return nil, err
	}
	return obj.(*firefly_v1.FireflyApplication), err
}

// Update takes the representation of a fireflyApplication and updates it. Returns the server's representation of the fireflyApplication, and an error, if there is any.
func (c *FakeFireflyApplications) Update(fireflyApplication *firefly_v1.FireflyApplication) (result *firefly_v1.FireflyApplication, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(fireflyapplicationsResource, c.ns, fireflyApplication), &firefly_v1.FireflyApplication{})

	if obj == nil {
		return nil, err
	}
	return obj.(*firefly_v1.FireflyApplication), err
}

// Delete takes name of the fireflyApplication and deletes it. Returns an error if one occurs.
func (c *FakeFireflyApplications) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(fireflyapplicationsResource, c.ns, name), &firefly_v1.FireflyApplication{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFireflyApplications) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(fireflyapplicationsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &firefly_v1.FireflyApplicationList{})
	return err
}

// Patch applies the patch and returns the patched fireflyApplication.
func (c *FakeFireflyApplications) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *firefly_v1.FireflyApplication, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(fireflyapplicationsResource, c.ns, name, data, subresources...), &firefly_v1.FireflyApplication{})

	if obj == nil {
		return nil, err
	}
	return obj.(*firefly_v1.FireflyApplication), err
}
